name: darwin
version: 0.1.0
author: Jesse Bouwman
description: Darwin/macOS platform services including kqueue event system and async networking
platform: darwin

sources:
  - src

tests:
  - tests

requires:
  - epsilon.core

provides:
  - epsilon.kqueue
  - epsilon.net