name: darwin
version: 1.0.0
author: Jesse Bouwman
description: Darwin/macOS specific functions
platform: darwin

sources:
  - src

tests:
  - tests

requires:
  - epsilon.core

provides:
  - darwin
  - epsilon.net
