name: lsp
description: Language Server Protocol implementation for Epsilon
version: 0.1.0
author: Epsilon Project
license: MIT

sources:
  - src

tests:
  - tests

dependencies:
  - core

provides:
  - epsilon.lsp
