name: linux
version: 1.0.0
author: Jesse Bouwman
description: Linux-specific functions (epoll networking)
platform: linux

sources:
  - src

tests:
  - tests

requires:
  - epsilon.core

provides:
  - linux
  - epsilon.net