(defpackage #:lib.regex
  (:use
   #:cl
   #:lib.symbol
   #:lib.type)
  (:shadow
   #:digit-char-p
   #:defconstant)
  (:export
   #:*allow-named-registers*
   #:*allow-quoting*
   #:*look-ahead-for-suffix*
   #:*optimize-char-classes*
   #:*property-resolver*
   #:*regex-char-code-limit*
   #:*use-bmh-matchers*
   #:all-matches
   #:all-matches-as-strings
   #:count-matches
   #:create-optimized-test-function
   #:create-scanner
   #:define-parse-tree-synonym
   #:do-matches
   #:do-matches-as-strings
   #:do-register-groups
   #:do-scans
   #:parse-string
   #:parse-tree-synonym
   #:regex-error
   #:regex-invocation-error
   #:regex-syntax-error
   #:regex-syntax-error-pos
   #:regex-syntax-error-string
   #:quote-meta-chars
   #:regex-apropos
   #:regex-apropos-list
   #:regex-replace
   #:regex-replace-all
   #:register-groups-bind
   #:scan
   #:scan-to-strings
   #:split))
