(:name "epsilon.core"
 :version "1.0.0"
 :author "Jesse Bouwman"
 :description "Core utility library for SBCL"
 :provides ("epsilon.binary"
           "epsilon.main"
           "epsilon.string"
           "epsilon.url"
           "epsilon.syntax" 
           "epsilon.edn"
           "epsilon.type"
           "epsilon.sequence"
           "epsilon.hex"
           "epsilon.map"
           "epsilon.list"
           "epsilon.symbol"
           "epsilon.function"
           "epsilon.log"
           "epsilon.table"
           "epsilon.char"
           "epsilon.protocol"
           "epsilon.digest"
           "epsilon.argparse"
           "epsilon.path"
           "epsilon.loader"
           "epsilon.time"))
