site_name: Epsilon - Modern Lisp Utilities
site_description: 'A utility library for SBCL with functional data structures, networking, and development tools'
site_author: 'Jesse Bouwman'
site_url: 'https://jbouwman.github.io/epsilon/'

# Repository
repo_name: 'epsilon-org/epsilon'
repo_url: 'https://github.com/epsilon-org/epsilon'
edit_uri: 'edit/main/docs/'

# Theme configuration
theme:
  name: material
  custom_dir: overrides/
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.instant     # Fast loading
    - navigation.tracking    # URL tracking
    - navigation.tabs       # Top-level tabs
    - navigation.sections   # Collapsible sections
    - navigation.expand     # Expand sections
    - navigation.prune      # Prune navigation
    - navigation.indexes    # Section index pages
    - toc.follow           # TOC follows scroll
    - toc.integrate        # Integrate TOC in navigation
    - search.suggest       # Search suggestions
    - search.highlight     # Highlight search terms
    - search.share         # Share search results
    - content.code.copy    # Copy code blocks
    - content.code.annotate # Code annotations
    - content.action.edit   # Edit page
    - content.action.view   # View source
    
  font:
    text: Inter
    code: JetBrains Mono

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs/examples/
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - def_list
  - md_in_html
  - tables
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

# Custom CSS and JavaScript
extra_css:
  - stylesheets/epsilon.css
  - stylesheets/lisp-syntax.css

extra_javascript:
  - javascripts/epsilon.js

# Navigation structure
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - REPL Usage: getting-started/repl.md
    - Project Setup: getting-started/project-setup.md
  
  - Core Library:
    - Overview: core/index.md
    - Data Structures:
      - Maps: core/data-structures/maps.md
      - Sequences: core/data-structures/sequences.md
      - Sets: core/data-structures/sets.md
    - String Processing: core/string-processing.md
    - File System: core/filesystem.md
    - Cryptography: core/cryptography.md
    - Time & UUID: core/time-uuid.md
  
  - Networking:
    - Overview: networking/index.md
    - HTTP Client: networking/http-client.md
    - HTTP Server: networking/http-server.md
    - TLS/SSL: networking/tls.md
    - WebSockets: networking/websockets.md
  
  - Development Tools:
    - Overview: dev-tools/index.md
    - Build System: dev-tools/build-system.md
    - Testing: dev-tools/testing.md
    - Package Management: dev-tools/packages.md
    - Hot Reload: dev-tools/hot-reload.md
    - LSP Server: dev-tools/lsp.md
  
  - Data Formats:
    - JSON: data-formats/json.md
    - YAML: data-formats/yaml.md
    - MessagePack: data-formats/msgpack.md
    - XML: data-formats/xml.md
  
  - Examples:
    - Gallery: examples/index.md
    - Web Applications: examples/web-apps.md
    - Data Processing: examples/data-processing.md
    - System Scripts: examples/scripts.md
    - Network Services: examples/network-services.md
  
  - API Reference:
    - Overview: api/index.md
    - epsilon.core: api/core.md
    - epsilon.lib.map: api/map.md
    - epsilon.lib.sequence: api/sequence.md
    - epsilon.lib.string: api/string.md
    - epsilon.sys.fs: api/filesystem.md
    - epsilon.lib.json: api/json.md
    - epsilon.net: api/networking.md
    - epsilon.tool.*: api/tools.md
  
  - Architecture:
    - Design Principles: architecture/principles.md
    - Module System: architecture/modules.md
    - Build Process: architecture/build.md
    - Performance: architecture/performance.md
  
  - Contributing:
    - Overview: contributing/index.md
    - Development Setup: contributing/setup.md
    - Code Style: contributing/style.md
    - Testing Guidelines: contributing/testing.md
    - Documentation: contributing/docs.md

# Social links and extra configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/epsilon-org/epsilon
    - icon: fontawesome/brands/discord
      link: https://discord.gg/epsilon
  version:
    provider: mike
    default: stable