site_name: Epsilon
site_description: Epsilon Environment - Technical Documentation
site_author: Jesse Bouwman
site_url: https://jbouwman.github.io/epsilon/

repo_name: epsilon
repo_url: https://github.com/jbouwman/epsilon
edit_uri: edit/main/docs/

docs_dir: docs
theme:
  name: material
  font:
    text: 'IBM Plex Mono'
    code: 'IBM Plex Mono'
  palette:
    # Light mode - technical documentation
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode - terminal aesthetic
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

extra_css:
  - stylesheets/epsilon.css

extra_javascript:
  - javascripts/lisp.js

plugins:
  - search:
      lang: en
  - mermaid2:
      version: 10.4.0

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - tables
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - toc:
      permalink: "¶"
      toc_depth: 3

nav:
  - Introduction:
    - Home: index.md
    - Getting Started: getting-started.md
    - Installation: installation.md
  - Libraries:
    - Overview: library/index.md
    - Data Structures: core/data-structures.md
    - JSON & YAML: core/json-yaml.md
    - Cryptography: core/cryptography.md
    - String Processing: core/strings.md
    - Networking: network/http.md
    - Threading: system/threading.md
    - Filesystem: system/filesystem.md
  - Tools:
    - Overview: tools/index.md
    - Build System: tools/build.md
    - Test Framework: tools/testing.md
    - Benchmarks: tools/benchmarks.md
  - Roadmaps:
    - Overview: roadmaps.md
    - LSP: roadmaps/001_lsp.md
    - Testing: roadmaps/002_testing_framework.md
    - Interactive Dev: roadmaps/003_interactive_development.md
    - Module System: roadmaps/004_module_system.md
    - Async Networking: roadmaps/005_async_networking.md
  - API Reference:
    - Overview: reference/index.md
    - epsilon.core:
      - Overview: reference/core/index.md
      - Data Structures:
        - epsilon.lib.map: reference/core/data-structures/map.md
        - epsilon.lib.sequence: reference/core/data-structures/sequence.md
        - epsilon.lib.vector: reference/core/data-structures/vector.md
        - epsilon.lib.set: reference/core/data-structures/set.md
        - epsilon.lib.list: reference/core/data-structures/list.md
      - Data Encoding:
        - epsilon.lib.json: reference/core/encoding/json.md
        - epsilon.lib.yaml: reference/core/encoding/yaml.md
        - epsilon.lib.msgpack: reference/core/encoding/msgpack.md
        - epsilon.lib.base64: reference/core/encoding/base64.md
        - epsilon.lib.hex: reference/core/encoding/hex.md
      - Cryptography:
        - epsilon.lib.digest: reference/core/crypto/digest.md
        - epsilon.lib.checksum: reference/core/crypto/checksum.md
      - String Processing:
        - epsilon.lib.string: reference/core/strings/string.md
        - epsilon.lib.char: reference/core/strings/char.md
        - epsilon.lib.regex: reference/core/strings/regex.md
      - System:
        - epsilon.sys.fs: reference/core/system/fs.md
        - epsilon.sys.thread: reference/core/system/thread.md
        - epsilon.sys.env: reference/core/system/env.md
      - Tools:
        - epsilon.tool.build: reference/core/tools/build.md
        - epsilon.tool.test: reference/core/tools/test.md
        - epsilon.tool.benchmark: reference/core/tools/benchmark.md
    - epsilon.net:
      - Overview: reference/net/index.md
      - epsilon.net: reference/net/core.md
    - epsilon.http:
      - Overview: reference/http/index.md
      - epsilon.http.client: reference/http/client.md
      - epsilon.http.server: reference/http/server.md
    - Examples: reference/examples.md

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jbouwman/epsilon
      name: Epsilon on GitHub
  generator: false

copyright: >
  Copyright &copy; 2025 Jesse Bouwman –
  <a href="#__consent">Change cookie settings</a>