;;;; Tests for xxHash implementation (XXH64 and XXH32)
;;;;
;;;; Test vectors from the xxHash reference implementation sanity check
;;;; (cli/xsum_sanity_check.c). The test buffer is generated by a PRNG
;;;; matching XSUM_fillTestBuffer.

(defpackage epsilon.ssl.xxhash-tests
  (:use :cl :epsilon.test :epsilon.ssl.test-support)
  (:local-nicknames
   (#:xxh #:epsilon.ssl.xxhash))
  (:enter t))

(in-package :epsilon.ssl.xxhash-tests)

;;; ---------------------------------------------------------------------------
;;; Helper functions
;;; ---------------------------------------------------------------------------

(defun make-test-buffer (len)
  "Generate the canonical xxHash test buffer (port of XSUM_fillTestBuffer).
   Uses a multiplicative PRNG: byteGen starts at PRIME32, each byte is
   byteGen>>56, then byteGen *= PRIME64."
  (let ((buf (make-array len :element-type '(unsigned-byte 8)))
        (byte-gen #x9E3779B1)
        (prime64  #x9E3779B185EBCA8D)
        (mask     #xFFFFFFFFFFFFFFFF))
    (loop for i from 0 below len
          do (setf (aref buf i) (logand #xFF (ash byte-gen -56)))
             (setf byte-gen (logand mask (* byte-gen prime64))))
    buf))

;;; ---------------------------------------------------------------------------
;;; XXH64 official test vectors
;;; ---------------------------------------------------------------------------

(deftest test-xxh64-empty-seed0
  "XXH64 of empty input, seed 0"
  (let ((input (make-array 0 :element-type '(unsigned-byte 8))))
    (assert-= (xxh:xxh64 input) #xEF46DB3751D8E999)))

(deftest test-xxh64-empty-seeded
  "XXH64 of empty input, seed 2654435761"
  (let ((input (make-array 0 :element-type '(unsigned-byte 8))))
    (assert-= (xxh:xxh64 input :seed 2654435761) #xAC75FDA2929B17EF)))

(deftest test-xxh64-1byte-seed0
  "XXH64 of 1 byte, seed 0"
  (let ((buf (make-test-buffer 1)))
    (assert-= (xxh:xxh64 buf) #xE934A84ADB052768)))

(deftest test-xxh64-1byte-seeded
  "XXH64 of 1 byte, seed 2654435761"
  (let ((buf (make-test-buffer 1)))
    (assert-= (xxh:xxh64 buf :seed 2654435761) #x5014607643A9B4C3)))

(deftest test-xxh64-4bytes-seed0
  "XXH64 of 4 bytes, seed 0"
  (let ((buf (make-test-buffer 4)))
    (assert-= (xxh:xxh64 buf) #x9136A0DCA57457EE)))

(deftest test-xxh64-14bytes-seed0
  "XXH64 of 14 bytes, seed 0"
  (let ((buf (make-test-buffer 14)))
    (assert-= (xxh:xxh64 buf) #x8282DCC4994E35C8)))

(deftest test-xxh64-14bytes-seeded
  "XXH64 of 14 bytes, seed 2654435761"
  (let ((buf (make-test-buffer 14)))
    (assert-= (xxh:xxh64 buf :seed 2654435761) #xC3BD6BF63DEB6DF0)))

(deftest test-xxh64-222bytes-seed0
  "XXH64 of 222 bytes (multi-stripe), seed 0"
  (let ((buf (make-test-buffer 222)))
    (assert-= (xxh:xxh64 buf) #xB641AE8CB691C174)))

(deftest test-xxh64-222bytes-seeded
  "XXH64 of 222 bytes (multi-stripe), seed 2654435761"
  (let ((buf (make-test-buffer 222)))
    (assert-= (xxh:xxh64 buf :seed 2654435761) #x20CB8AB7AE10C14A)))

;;; ---------------------------------------------------------------------------
;;; XXH32 official test vectors
;;; ---------------------------------------------------------------------------

(deftest test-xxh32-empty-seed0
  "XXH32 of empty input, seed 0"
  (let ((input (make-array 0 :element-type '(unsigned-byte 8))))
    (assert-= (xxh:xxh32 input) #x02CC5D05)))

(deftest test-xxh32-empty-seeded
  "XXH32 of empty input, seed 2654435761"
  (let ((input (make-array 0 :element-type '(unsigned-byte 8))))
    (assert-= (xxh:xxh32 input :seed 2654435761) #x36B78AE7)))

(deftest test-xxh32-1byte-seed0
  "XXH32 of 1 byte, seed 0"
  (let ((buf (make-test-buffer 1)))
    (assert-= (xxh:xxh32 buf) #xCF65B03E)))

(deftest test-xxh32-1byte-seeded
  "XXH32 of 1 byte, seed 2654435761"
  (let ((buf (make-test-buffer 1)))
    (assert-= (xxh:xxh32 buf :seed 2654435761) #xB4545AA4)))

(deftest test-xxh32-14bytes-seed0
  "XXH32 of 14 bytes, seed 0"
  (let ((buf (make-test-buffer 14)))
    (assert-= (xxh:xxh32 buf) #x1208E7E2)))

(deftest test-xxh32-14bytes-seeded
  "XXH32 of 14 bytes, seed 2654435761"
  (let ((buf (make-test-buffer 14)))
    (assert-= (xxh:xxh32 buf :seed 2654435761) #x6AF1D1FE)))

(deftest test-xxh32-222bytes-seed0
  "XXH32 of 222 bytes (multi-stripe), seed 0"
  (let ((buf (make-test-buffer 222)))
    (assert-= (xxh:xxh32 buf) #x5BD11DBD)))

(deftest test-xxh32-222bytes-seeded
  "XXH32 of 222 bytes (multi-stripe), seed 2654435761"
  (let ((buf (make-test-buffer 222)))
    (assert-= (xxh:xxh32 buf :seed 2654435761) #x58803C5F)))

;;; ---------------------------------------------------------------------------
;;; Hex output tests
;;; ---------------------------------------------------------------------------

(deftest test-xxh64-hex
  "xxh64-hex should return correct uppercase hex string"
  (let ((input (make-array 0 :element-type '(unsigned-byte 8))))
    (assert-equal (xxh:xxh64-hex input) "EF46DB3751D8E999")))

(deftest test-xxh32-hex
  "xxh32-hex should return correct uppercase hex string"
  (let ((input (make-array 0 :element-type '(unsigned-byte 8))))
    (assert-equal (xxh:xxh32-hex input) "02CC5D05")))

;;; ---------------------------------------------------------------------------
;;; Incremental hashing tests
;;; ---------------------------------------------------------------------------

(deftest test-xxh64-incremental-byte-by-byte
  "Incremental XXH64 byte-by-byte should match one-shot"
  (let* ((data (make-test-buffer 222))
         (oneshot (xxh:xxh64 data))
         (state (xxh:make-xxh64-state)))
    (loop for i from 0 below (length data)
          do (xxh:xxh64-update state data :start i :end (1+ i)))
    (assert-= (xxh:xxh64-finalize state) oneshot)))

(deftest test-xxh64-incremental-split
  "Incremental XXH64 with data split at every position"
  (let* ((data (make-test-buffer 100))
         (expected (xxh:xxh64 data)))
    (loop for split from 0 to (length data)
          do (let ((state (xxh:make-xxh64-state)))
               (xxh:xxh64-update state data :start 0 :end split)
               (xxh:xxh64-update state data :start split)
               (assert-= (xxh:xxh64-finalize state) expected)))))

(deftest test-xxh32-incremental-byte-by-byte
  "Incremental XXH32 byte-by-byte should match one-shot"
  (let* ((data (make-test-buffer 222))
         (oneshot (xxh:xxh32 data))
         (state (xxh:make-xxh32-state)))
    (loop for i from 0 below (length data)
          do (xxh:xxh32-update state data :start i :end (1+ i)))
    (assert-= (xxh:xxh32-finalize state) oneshot)))

(deftest test-xxh32-incremental-split
  "Incremental XXH32 with data split at every position"
  (let* ((data (make-test-buffer 50))
         (expected (xxh:xxh32 data)))
    (loop for split from 0 to (length data)
          do (let ((state (xxh:make-xxh32-state)))
               (xxh:xxh32-update state data :start 0 :end split)
               (xxh:xxh32-update state data :start split)
               (assert-= (xxh:xxh32-finalize state) expected)))))

;;; ---------------------------------------------------------------------------
;;; State copy tests
;;; ---------------------------------------------------------------------------

(deftest test-xxh64-copy
  "Copying XXH64 state should produce independent hasher"
  (let* ((data1 (string-to-bytes "Hello"))
         (data2a (string-to-bytes ", World!"))
         (data2b (string-to-bytes ", Lisp!"))
         (state1 (xxh:make-xxh64-state)))
    (xxh:xxh64-update state1 data1)
    (let ((state2 (xxh:xxh64-copy state1)))
      (xxh:xxh64-update state1 data2a)
      (xxh:xxh64-update state2 data2b)
      (let ((result1 (xxh:xxh64-finalize state1))
            (result2 (xxh:xxh64-finalize state2))
            (expected1 (xxh:xxh64 (string-to-bytes "Hello, World!")))
            (expected2 (xxh:xxh64 (string-to-bytes "Hello, Lisp!"))))
        (assert-= result1 expected1)
        (assert-= result2 expected2)
        (assert-not (= result1 result2))))))

(deftest test-xxh32-copy
  "Copying XXH32 state should produce independent hasher"
  (let* ((data1 (string-to-bytes "Hello"))
         (data2a (string-to-bytes ", World!"))
         (data2b (string-to-bytes ", Lisp!"))
         (state1 (xxh:make-xxh32-state)))
    (xxh:xxh32-update state1 data1)
    (let ((state2 (xxh:xxh32-copy state1)))
      (xxh:xxh32-update state1 data2a)
      (xxh:xxh32-update state2 data2b)
      (let ((result1 (xxh:xxh32-finalize state1))
            (result2 (xxh:xxh32-finalize state2))
            (expected1 (xxh:xxh32 (string-to-bytes "Hello, World!")))
            (expected2 (xxh:xxh32 (string-to-bytes "Hello, Lisp!"))))
        (assert-= result1 expected1)
        (assert-= result2 expected2)
        (assert-not (= result1 result2))))))

;;; ---------------------------------------------------------------------------
;;; Edge cases
;;; ---------------------------------------------------------------------------

(deftest test-xxh64-exact-stripe-size
  "XXH64 of exactly 32 bytes (one stripe, no remainder)"
  (let* ((data (make-test-buffer 32))
         (result (xxh:xxh64 data)))
    ;; Verify deterministic
    (assert-= result (xxh:xxh64 data))))

(deftest test-xxh64-stripe-plus-one
  "XXH64 of 33 bytes (one stripe + 1 byte remainder)"
  (let* ((data (make-test-buffer 33))
         (result (xxh:xxh64 data)))
    (assert-= result (xxh:xxh64 data))
    ;; Incremental should match
    (let ((state (xxh:make-xxh64-state)))
      (xxh:xxh64-update state data :start 0 :end 32)
      (xxh:xxh64-update state data :start 32)
      (assert-= (xxh:xxh64-finalize state) result))))

(deftest test-xxh32-exact-stripe-size
  "XXH32 of exactly 16 bytes (one stripe, no remainder)"
  (let* ((data (make-test-buffer 16))
         (result (xxh:xxh32 data)))
    (assert-= result (xxh:xxh32 data))))

(deftest test-xxh32-stripe-plus-one
  "XXH32 of 17 bytes (one stripe + 1 byte remainder)"
  (let* ((data (make-test-buffer 17))
         (result (xxh:xxh32 data)))
    (assert-= result (xxh:xxh32 data))
    (let ((state (xxh:make-xxh32-state)))
      (xxh:xxh32-update state data :start 0 :end 16)
      (xxh:xxh32-update state data :start 16)
      (assert-= (xxh:xxh32-finalize state) result))))

(deftest test-xxh64-large-input
  "XXH64 of 1000 bytes should be deterministic"
  (let* ((data (make-test-buffer 1000))
         (result (xxh:xxh64 data)))
    (assert-= result (xxh:xxh64 data))))

(deftest test-xxh32-large-input
  "XXH32 of 1000 bytes should be deterministic"
  (let* ((data (make-test-buffer 1000))
         (result (xxh:xxh32 data)))
    (assert-= result (xxh:xxh32 data))))

(deftest test-xxh64-seeded-incremental
  "Seeded incremental XXH64 should match seeded one-shot"
  (let* ((data (make-test-buffer 222))
         (seed 2654435761)
         (oneshot (xxh:xxh64 data :seed seed))
         (state (xxh:make-xxh64-state :seed seed)))
    (xxh:xxh64-update state data :start 0 :end 50)
    (xxh:xxh64-update state data :start 50 :end 100)
    (xxh:xxh64-update state data :start 100)
    (assert-= (xxh:xxh64-finalize state) oneshot)))

(deftest test-xxh32-seeded-incremental
  "Seeded incremental XXH32 should match seeded one-shot"
  (let* ((data (make-test-buffer 222))
         (seed 2654435761)
         (oneshot (xxh:xxh32 data :seed seed))
         (state (xxh:make-xxh32-state :seed seed)))
    (xxh:xxh32-update state data :start 0 :end 50)
    (xxh:xxh32-update state data :start 50 :end 100)
    (xxh:xxh32-update state data :start 100)
    (assert-= (xxh:xxh32-finalize state) oneshot)))

(deftest test-xxh64-start-end
  "XXH64 :start/:end should hash the subrange"
  (let* ((data (make-test-buffer 100))
         (sub (subseq data 10 60))
         (result-sub (xxh:xxh64 sub))
         (result-range (xxh:xxh64 data :start 10 :end 60)))
    (assert-= result-sub result-range)))

(deftest test-xxh32-start-end
  "XXH32 :start/:end should hash the subrange"
  (let* ((data (make-test-buffer 100))
         (sub (subseq data 10 60))
         (result-sub (xxh:xxh32 sub))
         (result-range (xxh:xxh32 data :start 10 :end 60)))
    (assert-= result-sub result-range)))
