name: Build Platform Containers

on:
  push:
    branches: [ main ]
    paths: [ '.docker/**' ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Linux container
      uses: docker/build-push-action@v5
      with:
        context: .
        file: .docker/linux/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/epsilon-linux:latest
        platforms: linux/amd64

  build-ci:
    runs-on: ubuntu-latest
    needs: build-linux
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push CI container
      uses: docker/build-push-action@v5
      with:
        context: .
        file: .docker/ci/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/epsilon-ci:latest
        platforms: linux/amd64

  build-windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Windows container
      run: |
        docker build -f .docker/windows/Dockerfile -t ghcr.io/${{ github.repository }}/epsilon-windows:latest .
        docker push ghcr.io/${{ github.repository }}/epsilon-windows:latest