name: Run Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install SBCL
      run: |
        sudo apt-get update
        sudo apt-get install -y sbcl

    - name: Install Nushell
      run: |
        wget -q https://github.com/nushell/nushell/releases/download/0.91.0/nu-0.91.0-x86_64-linux-gnu-full.tar.gz
        tar xf nu-0.91.0-x86_64-linux-gnu-full.tar.gz
        sudo mv nu-0.91.0-x86_64-linux-gnu-full/nu /usr/local/bin/

    - name: Run Unit Tests
      run: |
        chmod +x make
        ./make test
