name: Run Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}/epsilon-ci:latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Unit Tests
      run: |
        chmod +x make
        ./make test
