name: Run Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}/epsilon-ci:latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Unit Tests
      run: |
        chmod +x run.sh
        ./run.sh build epsilon.core
        ./run.sh test epsilon.core --format junit

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: success() || failure()
      with:
        report_paths: '**/TEST-epsilon.xml'