name: Validate - Quick Build Check

on:
  workflow_dispatch:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  quick-validate:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        platform: [core]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install SBCL (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y sbcl
        
    - name: Install SBCL (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install sbcl
        
    - name: Install SBCL (Windows)
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        # Use chocolatey for quick installation
        choco install sbcl -y
        
    - name: Verify SBCL
      run: sbcl --version
      
    - name: Quick build test
      shell: bash
      run: |
        chmod +x run.sh
        ./run.sh build --platform core
        
    - name: Quick test run
      shell: bash
      run: |
        # Just verify the build works, don't run full test suite
        echo "Build validation completed successfully on ${{ matrix.os }}"